modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
issueTrackerURL="https://github.com/Silverminer007/simpleportals/issues"
[[mods]]
modId="simpleportals_reloaded"
version="${file.jarVersion}"
displayName="Simple Portals Reloaded"
updateJSONURL="https://raw.githubusercontent.com/Silverminer007/MinecraftModsUpdateChecker/master/simpleportals.json"
logoFile="sp_logo.jpg"
credits="This mod was originally from Zarathul. All thanks goes there"
authors="Silverminer, Zarathul"
description='''
Adds portals for easy intra- and interdimensional travel.
'''
[[dependencies.simpleportals_reloaded]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simpleportals_reloaded]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
